### DISCUSSION TITLE
Leantime configuration

### DISCUSSION THREAD

**Discussion by gepd** [evertramos/nginx-proxy-automation#314] [Q&A] [answered]
Hello everyone,

I'm trying to use this image [docker-leantime](https://github.com/Leantime/docker-leantime) with `nginx-proxy-automation`

What I'm doing is:

```yml
version: '3.3'

services:
   db:
     image: mysql:5.7
     container_name: mysql_leantime
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
         MYSQL_ROOT_PASSWORD: '321.qwerty'
         MYSQL_DATABASE: 'leantime'
         MYSQL_USER: 'admin'
         MYSQL_PASSWORD: '321.qwerty'
         # added this lines
         VIRTUAL_HOST: ${HOST_NAME}
         VIRTUAL_PORT: ${PORT}
         LETSENCRYPT_HOST: ${HOST_NAME}
         LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
     ports:
       - "3306:3306"
     networks: # set network
      - webproxy
     command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
   web:
     image: leantime/leantime:latest
     container_name: leantime
     environment:
         LEAN_DB_HOST: 'mysql_leantime'
         LEAN_DB_USER: 'admin'
         LEAN_DB_PASSWORD: '321.qwerty'
         LEAN_DB_DATABASE: 'leantime'
     expose:
      - "${PORT}"
     ports:
       - "9000:9000"
       - "${PORT}:80"
     depends_on:
       - db
volumes:
    db_data: {}
networks: # and this
  webproxy:
    external: true
```

[here](https://github.com/Leantime/docker-leantime/blob/master/config/app.conf) is the apache configuration but I don't can make it work with nginx automation

**Comment by evertramos** [comment]
Hello @gepd!

You must add the network and the proxy environment variables in leantime container, the web service in your docker-compose file. 

```bash
version: '3.3'

services:
   db:
     image: mysql:5.7
     container_name: mysql_leantime
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
         MYSQL_ROOT_PASSWORD: '321.qwerty'
         MYSQL_DATABASE: 'leantime'
         MYSQL_USER: 'admin'
         MYSQL_PASSWORD: '321.qwerty'
     ports:
       - "3306:3306"
     command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
   web:
     image: leantime/leantime:latest
     container_name: leantime
     environment:
         LEAN_DB_HOST: 'mysql_leantime'
         LEAN_DB_USER: 'admin'
         LEAN_DB_PASSWORD: '321.qwerty'
         LEAN_DB_DATABASE: 'leantime'
         # added this lines
         VIRTUAL_HOST: ${HOST_NAME}
         VIRTUAL_PORT: ${PORT}
         LETSENCRYPT_HOST: ${HOST_NAME}
         LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
     networks: # set network
      - webproxy
     expose:
      - "${PORT}"
     ports:
       - "9000:9000"
       - "${PORT}:80"
     depends_on:
       - db
volumes:
    db_data: {}
networks: # and this
  webproxy:
    external: true
```

**Comment by gepd** [comment]
thanks @evertramos I was doing that, I copied the file wrongly

When I open the `default.conf` file I see

```php
upstream subdomain.domain.com {
  # Cannot connect to network of this container
  server 127.0.0.1 down;
  ## Can be connected with "webproxy" network
  # leantime
  server 172.30.0.7:1500;
}
```

`1500` is the port I'm defining in the `.env` file

**Reply by evertramos** [reply]
Dude, 

Remove this line `- "${PORT}:80"` from your file, stop, wait 5 seconds and start again.... did you read the docs?

Why are you exposing this door? You can remove the `expose` as well, unless is a requirement for leantime...

**Comment by gepd** [comment, marked as answer]
Dude, 

before I write here I have read the docs, but I don't see how having a port opened can be the source of the problem I'm having.

Removing the port and `expose` do not solved my problem

(I was opening the port for debugging)

**Reply by evertramos** [reply]
don't get me wrong... the VIRTUAL_PORT is the one will used by the proxy... that's why it is using the port 1500, if you remove this binding or use another variable or even delete this environment variable from your compose file it will redirect to you service as expected.

**Reply by evertramos** [reply]
did you manage to solve it?

**Reply by gepd** [reply]
I still don't solved, but now I'm almost sure It's a dns problem, not nginx automation, I've others containers working with the same configuration

I'm busy with other problem but I'll comment here as soon as I have the answer

**Reply by evertramos** [reply]
Did you manage to solve it?

**Reply by gepd** [reply]
I finally solved, the problem was as I suspected with the DNS, the domain was not redirecting to the correct server, the nginx-letsencript was showing an error that the domain used was not public, that was the first hint to solve the problem. After change the DNS I could remove the `ports` and `VIRTUAL_PORT` and everything worked as expected.

Thanks for your help!

**Reply by evertramos** [reply]
would you mind post the final docker-compose.yml that worked, mark as reponse and clonse the discussion? thanks

**Reply by gepd** [reply]
```yml
version: '3.3'
services:
   db:
     image: mysql:5.7
     container_name: mysql_leantime
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
         MYSQL_ROOT_PASSWORD: '321.qwerty'
         MYSQL_DATABASE: 'leantime'
         MYSQL_USER: 'admin'
         MYSQL_PASSWORD: '321.qwerty'
     ports:
       - "3306:3306"
     command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
   web:
     image: leantime/leantime:latest
     container_name: leantime
     environment:
         LEAN_DB_HOST: 'mysql_leantime'
         LEAN_DB_USER: 'admin'
         LEAN_DB_PASSWORD: '321.qwerty'
         LEAN_DB_DATABASE: 'leantime'
         VIRTUAL_HOST: ${HOST_NAME}
         LETSENCRYPT_HOST: ${HOST_NAME}
         LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
     networks:
      - webproxy
     depends_on:
       - db
volumes:
    db_data: {}
networks:
  webproxy:
    external: true
```

This is the file I'm currently using
