### DISCUSSION TITLE
Request forwarded to wrong container with subdomains

### DISCUSSION THREAD

**Discussion by Twois** [evertramos/nginx-proxy-automation#340] [Q&A] [answered]
I have two subdomain (dev.domain.com) and (test.domain.com)

Both are placed in different folders
home/
 - proxy
 - dev.domain.com
 - test.domain.com
 
AS I see, sometimes (~50%) when i surf on dev.domain.com and call an api request that not exist on test.domain.com i got 404.

Because of this i think some times nginx-proxy-automation forward the request to test.domain.com instead of dev.domain.com

The other reason why I think it's a forward problem, because if I stop test.domain.com all request successful.

I have not found any information about there is a problem with subdomains.

Here are some conf:

**dev.domain.com**

.env
```
LETSENCRYPT_EMAIL=mail@ofme.com
DOMAINS=dev.domain.com
NETWORK=proxy
NGINX_PORT=3000
```
docker-compose.yml
```
version: '3.8'
services:
    #NGINX
    nginx:
        restart: always
        
        image: nginx:1.19.6-alpine

        env_file: 
            - .env

        environment: 
            BACKEND_PORT: ${SERVER_PORT}
            PUBLIC_PORT: ${PUBLIC_PORT}
            VIRTUAL_HOST: ${DOMAINS}
            VIRTUAL_PORT: ${NGINX_PORT}
            LETSENCRYPT_HOST: ${DOMAINS}
            LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}

        volumes:
            - ./nginx/prod.default.conf.template:/etc/nginx/templates/default.conf.template
            - ./frontend/dist/browser:/usr/share/nginx/html
        
        ports: 
            - '${NGINX_PORT}:80'
        
        logging: 
            driver: none

    #BACKEND
    backend:
        build:
            dockerfile: Dockerfile
            context: ./backend

        env_file: 
            - .env

        environment: 
            MAIL_TO_OAM: ${MAIL_TO_OAM}
            MAIL_TO_WEBSITE: ${MAIL_TO_WEBSITE}
            MAIL_FROM_WEBSITE: ${MAIL_FROM_WEBSITE}

            SMTP_HOST: ${SMTP_HOST}
            SMTP_PORT: ${SMTP_PORT}
            SMTP_USER: ${SMTP_USER}
            SMTP_SECURE: ${SMTP_SECURE}
            SMTP_PASSWORD: ${SMTP_PASSWORD}

            MONGO_DB: ${MONGO_DB}
            MONGO_PORT: ${MONGO_PORT}
            MONGO_HOST: ${MONGO_HOST}
            MONGO_USERNAME: ${MONGO_USERNAME}
            MONGO_PASSWORD: ${MONGO_PASSWORD}
            MONGO_PROTOCOL: ${MONGO_PROTOCOL}
            MONGO_AUTHSOURCE: ${MONGO_AUTHSOURCE}

            SERVER_HOST: ${SERVER_HOST}
            SERVER_PORT: ${SERVER_PORT}
            SERVER_PATH: ${SERVER_PATH}
            SERVER_ENVIRONMENT: ${SERVER_ENVIRONMENT}
            DEBUG_COLORS: "true"
            TERM: xterm-256color
            COLORTERM: truecolor
        
        volumes:
            - ./backend:/app
        
        entrypoint: ["npm", "run", "serve"]

networks:
    default:
        external:
            name: ${NETWORK}
```

**test.domain.com**

.env
```
LETSENCRYPT_EMAIL=mail@ofme.com
DOMAINS=test.domain.com
NETWORK=proxy
NGINX_PORT=3001
```

docker-compose.yml

```yml
version: '3.8'
services:
    #NGINX
    nginx:
        restart: always
        
        image: nginx:1.19.6-alpine

        env_file: 
            - .env

        environment: 
            BACKEND_PORT: ${SERVER_PORT}
            PUBLIC_PORT: ${PUBLIC_PORT}
            VIRTUAL_HOST: ${DOMAINS}
            VIRTUAL_PORT: ${NGINX_PORT}
            LETSENCRYPT_HOST: ${DOMAINS}

        volumes:
            - ./nginx/prod.default.conf.template:/etc/nginx/templates/default.conf.template
            - ./frontend/dist/browser:/usr/share/nginx/html
        
        ports: 
            - '${NGINX_PORT}:80'
        
        logging: 
            driver: none

    #BACKEND
    backend:
        build:
            dockerfile: Dockerfile
            context: ./backend

        env_file: 
            - .env

        environment: 
            MAIL_TO_OAM: ${MAIL_TO_OAM}
            MAIL_TO_WEBSITE: ${MAIL_TO_WEBSITE}
            MAIL_FROM_WEBSITE: ${MAIL_FROM_WEBSITE}

            SMTP_HOST: ${SMTP_HOST}
            SMTP_PORT: ${SMTP_PORT}
            SMTP_USER: ${SMTP_USER}
            SMTP_SECURE: ${SMTP_SECURE}
            SMTP_PASSWORD: ${SMTP_PASSWORD}

            MONGO_DB: ${MONGO_DB}
            MONGO_PORT: ${MONGO_PORT}
            MONGO_HOST: ${MONGO_HOST}
            MONGO_USERNAME: ${MONGO_USERNAME}
            MONGO_PASSWORD: ${MONGO_PASSWORD}
            MONGO_PROTOCOL: ${MONGO_PROTOCOL}
            MONGO_AUTHSOURCE: ${MONGO_AUTHSOURCE}

            SERVER_HOST: ${SERVER_HOST}
            SERVER_PORT: ${SERVER_PORT}
            SERVER_PATH: ${SERVER_PATH}
            SERVER_ENVIRONMENT: ${SERVER_ENVIRONMENT}
            DEBUG_COLORS: "true"
            TERM: xterm-256color
            COLORTERM: truecolor
        
        volumes:
            - ./backend:/app
        
        entrypoint: ["npm", "run", "serve"]

networks:
    default:
        external:
            name: ${NETWORK}
```
