### DISCUSSION TITLE
VIRTUAL_PATH support

### DISCUSSION THREAD

**Discussion by darkopetreski** [evertramos/nginx-proxy-automation#352] [Q&A] [answered]
Can VIRTUAL_PATH and VIRTUAL_DEST be supported as in the nginx-proxy/nginx-proxy ?

**Comment by evertramos** [comment, marked as answer]
@darkopetreski  sure it can, just make sure to use the correct image versions as of nginx-proxy files and update the template:

```bash
./fresh-start.sh --update-nginx-template
```

In fact, we just automate the instalation, using the nginx-proxy itself.

**Comment by darkopetreski** [comment]
Thank you

**Comment by OliverTempel** [comment]
@darkopetreski did it work? 
Everytime where i add virtual path to the docker-compose file my container is not reachable. and yes i had updated nginx template as shown above.

Is there more to consider?

**Reply by darkopetreski** [reply]
For me it is working. You need to use virtual_path both the containers:

```
  web:
    image: ...
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PORT: 80
      VIRTUAL_PATH: /
      
  shop:
    image: ...
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PORT: 80
      VIRTUAL_PATH: /shop
```
