### ISSUE TITLE
nginx mail server configuration issue

### ISSUE THREAD

**Issue by allanext** [evertramos/nginx-proxy-automation#264]
I've been using your nginx-proxy-automation for all my web docker containers and I'm finally moving also multiple mail services but it looks like the normal configuration is not sufficient.

I've also noticed that SSL is not responding properly:
```
openssl s_client -showcerts -connect mail2.mydomain.com:465
CONNECTED(00000005)
4425047724:error:140040E5:SSL routines:CONNECT_CR_SRVR_HELLO:ssl handshake failure:/AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-56.60.2/libressl-2.8/ssl/ssl_pkt.c:585:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 0 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    Start Time: 1617135872
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
---
```
From the mail container I can ping outside and the nginx container can ping the mail container.

Netcat gives mixed results:
```
users-Mac-Pro:~ user$ nc -zv mail2.mydomain.com 465
Connection to mail2.mydomain.com port 465 [tcp/urd] succeeded!
users-Mac-Pro:~ user$ nc -zv mail2.mydomain.com 993
Connection to mail2.mydomain.com port 993 [tcp/imaps] succeeded!
users-Mac-Pro:~ user$ nc -zv mail2.mydomain.com 25
nc: connectx to mail2.mydomain.com port 25 (tcp) failed: Operation timed out
```
above perhaps because port 25 has STARTTLS and not straight TLS.

Here's the nginx docker-compose configuration:
```
The nginx docker-compose file:
version: '3'
services:
  nginx-web:
    image: nginx:stable-alpine
    labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: ${NGINX_WEB:-nginx-web}
    restart: always
    ports:
      - "${IP:-0.0.0.0}:${DOCKER_HTTP:-80}:80"
      - "${IP:-0.0.0.0}:${DOCKER_HTTPS:-443}:443"
      - "${IP:-0.0.0.0}:25:25"
      - "${IP:-0.0.0.0}:143:143"
      - "${IP:-0.0.0.0}:993:993"
      - "${IP:-0.0.0.0}:465:465"
      - "${IP:-0.0.0.0}:587:587"
    volumes:
      - ${NGINX_FILES_PATH:-./data}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH:-./data}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH:-./data}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH:-./data}/certs:/etc/nginx/certs:ro
      - ${NGINX_FILES_PATH:-./data}/htpasswd:/etc/nginx/htpasswd:ro
    logging:
      driver: ${NGINX_WEB_LOG_DRIVER:-json-file}
      options:
        max-size: ${NGINX_WEB_LOG_MAX_SIZE:-4m}
        max-file: ${NGINX_WEB_LOG_MAX_FILE:-10}

  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup ${NGINX_WEB:-nginx-web} -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: ${DOCKER_GEN:-nginx-gen}
    restart: always
    environment:
      SSL_POLICY: ${SSL_POLICY:-Mozilla-Intermediate}
    volumes:
      - ${NGINX_FILES_PATH:-./data}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH:-./data}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH:-./data}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH:-./data}/certs:/etc/nginx/certs:ro
      - ${NGINX_FILES_PATH:-./data}/htpasswd:/etc/nginx/htpasswd:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    logging:
      driver: ${NGINX_GEN_LOG_DRIVER:-json-file}
      options:
        max-size: ${NGINX_GEN_LOG_MAX_SIZE:-2m}
        max-file: ${NGINX_GEN_LOG_MAX_FILE:-10}

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:stable
    container_name: ${LETS_ENCRYPT:-nginx-letsencrypt}
    restart: always
    volumes:
      - ${NGINX_FILES_PATH:-./data}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH:-./data}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH:-./data}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH:-./data}/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: ${DOCKER_GEN:-nginx-gen}
      NGINX_PROXY_CONTAINER: ${NGINX_WEB:-nginx-web}
    logging:
      driver: ${NGINX_LETSENCRYPT_LOG_DRIVER:-json-file}
      options:
        max-size: ${NGINX_LETSENCRYPT_LOG_MAX_SIZE:-2m}
        max-file: ${NGINX_LETSENCRYPT_LOG_MAX_FILE:-10}

networks:
  default:
    external:
      name: ${NETWORK:-webproxy}
```

And finally my mail server configuration:
```
 version: '3.8'

services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:9.1.0
    hostname: ${HOSTNAME}
    domainname: ${DOMAINNAME}
    container_name: ${CONTAINER_NAME}
    env_file: mailserver.env
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    networks: 
      - webproxy
    expose:
      - 25
      - 143
      - 465
      - 587
      - 993
    volumes:
      - ./maildata:/var/mail
      - ./mailstate:/var/mail-state
      - ./maillogs:/var/log/mail
      - /etc/localtime:/etc/localtime:ro
      - ./config/:/tmp/docker-mailserver/${SELINUX_LABEL}
      - /home/ec2-user/docker/nginx/data/certs:/etc/letsencrypt/live:ro
    restart: always
    cap_add: [ "NET_ADMIN", "SYS_PTRACE" ]
    environment:
      ENABLE_SPAMASSASSIN: 1
      SPAMASSASSIN_SPAM_TO_INBOX: 1
      ENABLE_CLAMAV: 1
      ENABLE_FAIL2BAN: 1
      ENABLE_POSTGREY: 1
      ENABLE_SASLAUTHD: 0
      ONE_DIR: 1
      DMS_DEBUG: 1
      VIRTUAL_HOST: $DOMAINS
      LETSENCRYPT_HOST: $DOMAINS
      LETSENCRYPT_EMAIL: $LETSENCRYPT_EMAIL

networks:
  webproxy:
    external: true
```

My questions would be:
- is nginx configure for mail support as indicated in the configuration [https://docs.nginx.com/nginx/admin-guide/mail-proxy/mail-proxy/](https://docs.nginx.com/nginx/admin-guide/mail-proxy/mail-proxy/)?
- if not I could let the mail server handle the TLS with its certificates. But how can I say that those ports (25,143,465,587,993) are just pass through for the nginx reverse proxy? in this case I would use nginx only as a reverse proxy and nginx-letsencrypt to generate the certificates but not to strip out TLS layer.

Thank you!
