### ISSUE TITLE
[BUG] After update all acme and https requests are failing

### ISSUE THREAD

**Issue by Zageron** [evertramos/nginx-proxy-automation#278]
**Describe the bug**
After upgrading my websites started failing with PR_END_OF_FILE_ERROR.
I destroyed my nginx-proxy-automation setup and started from fresh, to the same result.
Currently going to try to back up to a version from a few months ago to see if that works.

**To Reproduce**
1. Clone fresh repository at master or at a tag.
2. Use fresh start with ipv6.
3. Try to browse to website. (PR_END_OF_FILE_ERROR)
4. In logs, some website succeed at letsencrypt, some do not.
5. Browsing to the failing acme token requests result in a 500 error.
6. The recommended steps for ./test.sh result in the same issues.

**Expected behavior**
After 10-25 seconds the site should just work, as it always has.

**Server info (please complete the following information):**
 - Linux release: Linux ubuntu-s-2vcpu-2gb-amd-sfo3-02 5.8.0-50-generic #56-Ubuntu SMP Mon Apr 12 17:18:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
 - Server type: Digital Ocean Droplet
 - Docker version: Docker version 20.10.2, build 20.10.2-0ubuntu1~20.10.1
 - docker-compose version:
   ```
   docker-compose version 1.28.5, build c4eb3a1f
docker-py version: 4.4.4
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
   ```

```
docker-gen-auto     | 2021/05/08 03:47:24 Generated '/etc/nginx/conf.d/default.conf' from 6 containers
docker-gen-auto     | 2021/05/08 03:47:24 Sending container 'proxy-web-auto' signal '1'
letsencrypt-auto    | Info: running acme-companion version v2.1.0
letsencrypt-auto    | Info: Custom Diffie-Hellman group found, generation skipped.
letsencrypt-auto    | Reloading nginx docker-gen (using separate container docker-gen-auto)...
letsencrypt-auto    | Reloading nginx (using separate container 0753f3727013a8fbc8d36f289c96f78296cf4d00735876b6348573560dba0c13)...
letsencrypt-auto    | 2021/05/08 03:43:46 Generated '/app/letsencrypt_service_data' from 6 containers
letsencrypt-auto    | 2021/05/08 03:43:46 Running '/app/signal_le_service'
letsencrypt-auto    | 2021/05/08 03:43:46 Watching docker events
letsencrypt-auto    | 2021/05/08 03:43:46 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
letsencrypt-auto    | Reloading nginx docker-gen (using separate container docker-gen-auto)...
letsencrypt-auto    | Reloading nginx (using separate container 0753f3727013a8fbc8d36f289c96f78296cf4d00735876b6348573560dba0c13)...
letsencrypt-auto    | Creating/renewal nextcloud.zageron.com certificates... (nextcloud.zageron.com)
letsencrypt-auto    | [Sat May  8 03:43:47 UTC 2021] Using CA: https://acme-v02.api.letsencrypt.org/directory
letsencrypt-auto    | [Sat May  8 03:43:47 UTC 2021] Creating domain key
letsencrypt-auto    | [Sat May  8 03:43:48 UTC 2021] The domain key is here: /etc/acme.sh/hello@zageron.com/nextcloud.zageron.com/nextcloud.zageron.com.key
letsencrypt-auto    | [Sat May  8 03:43:48 UTC 2021] Single domain='nextcloud.zageron.com'
letsencrypt-auto    | [Sat May  8 03:43:48 UTC 2021] Getting domain auth token for each domain
letsencrypt-auto    | [Sat May  8 03:43:49 UTC 2021] Getting webroot for domain='nextcloud.zageron.com'
letsencrypt-auto    | [Sat May  8 03:43:49 UTC 2021] Verifying: nextcloud.zageron.com
letsencrypt-auto    | [Sat May  8 03:43:52 UTC 2021] nextcloud.zageron.com:Verify error:Fetching http://nextcloud.zageron.com/.well-known/acme-challenge/pC7po20RJGSXgTa1SyagmYOBhh7nxoo4yXY3mKGib-o: Connection reset by peer
letsencrypt-auto    | [Sat May  8 03:43:52 UTC 2021] Please check log file for more details: /dev/null
letsencrypt-auto    | Creating/renewal www.zageron.com certificates... (www.zageron.com zageron.com)
letsencrypt-auto    | [Sat May  8 03:43:53 UTC 2021] Using CA: https://acme-v02.api.letsencrypt.org/directory
letsencrypt-auto    | [Sat May  8 03:43:53 UTC 2021] Creating domain key
letsencrypt-auto    | [Sat May  8 03:43:54 UTC 2021] The domain key is here: /etc/acme.sh/hello@zageron.com/www.zageron.com/www.zageron.com.key
letsencrypt-auto    | [Sat May  8 03:43:54 UTC 2021] Multi domain='DNS:www.zageron.com,DNS:zageron.com'
letsencrypt-auto    | [Sat May  8 03:43:54 UTC 2021] Getting domain auth token for each domain
letsencrypt-auto    | [Sat May  8 03:43:56 UTC 2021] Getting webroot for domain='www.zageron.com'
letsencrypt-auto    | [Sat May  8 03:43:56 UTC 2021] Getting webroot for domain='zageron.com'
letsencrypt-auto    | [Sat May  8 03:43:56 UTC 2021] Verifying: www.zageron.com
letsencrypt-auto    | [Sat May  8 03:43:59 UTC 2021] www.zageron.com:Verify error:Fetching http://www.zageron.com/.well-known/acme-challenge/gEnAnsToAEkc-f4luYpfh4s_MVgGR1mJta73Yr-T3Ng: Connection reset by peer
letsencrypt-auto    | [Sat May  8 03:43:59 UTC 2021] Please check log file for more details: /dev/null
letsencrypt-auto    | Sleep for 3600s
letsencrypt-auto    | 2021/05/08 03:47:05 Received event start for container 03645e1a05ed
letsencrypt-auto    | 2021/05/08 03:47:10 Debounce minTimer fired
letsencrypt-auto    | 2021/05/08 03:47:10 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
letsencrypt-auto    | 2021/05/08 03:47:18 Received event die for container 03645e1a05ed
letsencrypt-auto    | 2021/05/08 03:47:19 Received event stop for container 03645e1a05ed
letsencrypt-auto    | 2021/05/08 03:47:24 Debounce minTimer fired
letsencrypt-auto    | 2021/05/08 03:47:24 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
proxy-web-auto      | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
proxy-web-auto      | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
proxy-web-auto      | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
proxy-web-auto      | 10-listen-on-ipv6-by-default.sh: Getting the checksum of /etc/nginx/conf.d/default.conf
proxy-web-auto      | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
proxy-web-auto      | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
proxy-web-auto      | /docker-entrypoint.sh: Configuration complete; ready for start up
proxy-web-auto      | nextcloud.zageron.com 207.216.192.148 - - [08/May/2021:03:44:02 +0000] "GET /.well-known/acme-challenge/pC7po20RJGSXgTa1SyagmYOBhh7nxoo4yXY3mKGib-o HTTP/2.0" 500 177 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:90.0) Gecko/20100101 Firefox/90.0"
```

**Comment by evertramos** [comment]
Hello @Zageron!

I am very sorry to inform you that our last commit were done with a bug in the _basescript_ repo, which passes in my test. So, I would like you to try again and see if all will work as expected. 

Please direct contact me if you face any new issues on that update.

**Comment by Zageron** [comment]
Still getting the same issue from a fresh deploy.
```
letsencrypt-auto                      | Sleep for 3600s
letsencrypt-auto                      | Creating/renewal nextcloud.zageron.com certificates... (nextcloud.zageron.com)
letsencrypt-auto                      | [Mon May 10 03:05:59 UTC 2021] Using CA: https://acme-v02.api.letsencrypt.org/directory
letsencrypt-auto                      | [Mon May 10 03:05:59 UTC 2021] Creating domain key
letsencrypt-auto                      | [Mon May 10 03:05:59 UTC 2021] The domain key is here: /etc/acme.sh/hello@zageron.com/nextcloud.zageron.com/nextcloud.zageron.com.key
letsencrypt-auto                      | [Mon May 10 03:05:59 UTC 2021] Single domain='nextcloud.zageron.com'
letsencrypt-auto                      | [Mon May 10 03:05:59 UTC 2021] Getting domain auth token for each domain
letsencrypt-auto                      | [Mon May 10 03:06:01 UTC 2021] Getting webroot for domain='nextcloud.zageron.com'
letsencrypt-auto                      | [Mon May 10 03:06:01 UTC 2021] Verifying: nextcloud.zageron.com
letsencrypt-auto                      | [Mon May 10 03:06:04 UTC 2021] nextcloud.zageron.com:Verify error:Fetching http://nextcloud.zageron.com/.well-known/acme-challenge/R1Bx_NZ-pw8qmiqaBJ7Al1d8SNQ08r9SG5SC212B7ts: Connection reset by peer
letsencrypt-auto                      | [Mon May 10 03:06:04 UTC 2021] Please check log file for more details: /dev/null
letsencrypt-auto                      | Creating/renewal www.zageron.com certificates... (www.zageron.com zageron.com)
letsencrypt-auto                      | [Mon May 10 03:06:05 UTC 2021] Using CA: https://acme-v02.api.letsencrypt.org/directory
letsencrypt-auto                      | [Mon May 10 03:06:05 UTC 2021] Creating domain key
letsencrypt-auto                      | [Mon May 10 03:06:05 UTC 2021] The domain key is here: /etc/acme.sh/hello@zageron.com/www.zageron.com/www.zageron.com.key
letsencrypt-auto                      | [Mon May 10 03:06:05 UTC 2021] Multi domain='DNS:www.zageron.com,DNS:zageron.com'
letsencrypt-auto                      | [Mon May 10 03:06:05 UTC 2021] Getting domain auth token for each domain
letsencrypt-auto                      | [Mon May 10 03:06:07 UTC 2021] Getting webroot for domain='www.zageron.com'
letsencrypt-auto                      | [Mon May 10 03:06:07 UTC 2021] Getting webroot for domain='zageron.com'
letsencrypt-auto                      | [Mon May 10 03:06:07 UTC 2021] Verifying: www.zageron.com
letsencrypt-auto                      | [Mon May 10 03:06:10 UTC 2021] www.zageron.com:Verify error:Fetching http://www.zageron.com/.well-known/acme-challenge/phsdgFJ2k1vcaZvMbyQAZNGUxAh_hs0mtR8e3LZi3iY: Connection reset by peer
letsencrypt-auto                      | [Mon May 10 03:06:10 UTC 2021] Please check log file for more details: /dev/null
```

.env
```
#-----------------------------------------------------------------------
#
# https://github.com/evertramos/nginx-proxy-automation
#
# NGINX Proxy automation
#
# This is the .env file to set up nginx-proxy in your environment
#
#-----------------------------------------------------------------------

#-----------------------------------------------------------------------
#
# NGINX-Proxy containers/service
#
# The variables below is used to set the containers name for the nginx-proxy
# and the image version for each service, please note that if you use our script
# we will replace the service name in docker-compose file with the container name
#
NGINX_WEB_SEVICE_NAME=proxy-web-auto
NGINX_IMAGE_VERSION=stable-alpine

DOCKER_GEN_SEVICE_NAME=docker-gen-auto
DOCKER_GEN_IMAGE_VERSION=0.7.6

LETS_ENCRYPT_SEVICE_NAME=letsencrypt-auto
NGINX_PROXY_COMPANION_IMAGE_VERSION=2.1

#-----------------------------------------------------------------------
#
# IP address of the external interface
#
# The IP address below is used to bind your local services to the internet
# please make sure you use the correct address otherwise your proxy will not
# work properly, '0.0.0.0' will work, but we recommend to update this variable
#
IPv4=143.198.233.36
IPv6=2604:a880:4:1d0::227:1000

#-----------------------------------------------------------------------
#
# Default network name
#
# The network name set below is used by the proxy to forward internet requests
# to the correct containers in your environment, so please make sure to add this
# network in all docker containers, otherwise it will break the proxy redirection
#
NETWORK=proxy

#-----------------------------------------------------------------------
#
# Data path for the nginx-proxy files
#
# The variable below will be used to place all files used by the nginx-proxy
# please consider including this folder to your backup services, once all config
# files, settings and certificates will be placed here in case you need to recover
#
NGINX_FILES_PATH=/home/zageron/proxy/bin/../data

#-----------------------------------------------------------------------
#
# Docker logging settings
#
# Logs! Very important, right? But if you do not clean it up, it might causes you
# issues on disk space over time, so keep in mind to set this log options making sure
# you will have the least to audit, any further information on that please check the docs
#
# https://docs.docker.com/config/containers/logging/configure/
#
NGINX_WEB_LOG_DRIVER=json-file
NGINX_WEB_LOG_MAX_SIZE=4m
NGINX_WEB_LOG_MAX_FILE=10

NGINX_GEN_LOG_DRIVER=json-file
NGINX_GEN_LOG_MAX_SIZE=2m
NGINX_GEN_LOG_MAX_FILE=10

NGINX_LETSENCRYPT_LOG_DRIVER=json-file
NGINX_LETSENCRYPT_LOG_MAX_SIZE=2m
NGINX_LETSENCRYPT_LOG_MAX_FILE=10

#-----------------------------------------------------------------------
#
# Docker ports that should be binded by the proxy
#
# This option were added by a contributor long ago, so might be a very specific case
# where you might need to change http and https port number, keep in mind that changes
# on that setting might will break the auto renewing Let's Encrypt certificate services
#
DOCKER_HTTP_=80
DOCKER_HTTPS=443

#-----------------------------------------------------------------------
#
# SSL policy (defaults to Mozilla-Intermediate)
#
# This also was added by a contributor which sets the default cipher configuration
# to the nginx-proxy container, which has the 'Mozilla-Intermediate' as default value
# plase make sure you take a good look at options in the url below before messing around
#
# https://github.com/nginx-proxy/nginx-proxy#how-ssl-support-works
#
SSL_POLICY=Mozilla-Modern

#-----------------------------------------------------------------------
#
# Let's Encrypt default email
#
# You might want to inform a default email to Let's Encrypt certificate once it is
# a required parameter in order to issue the new certificate. This information will be
# replaced by the LETSENCRYPT_EMAIL environment varibale present in your docker container
#
DEFAULT_EMAIL=hello@adambryant.com
```

docker-compose
```
version: '3'

services:
  nginx-proxy-automation-web:
    image: nginx:${NGINX_IMAGE_VERSION:-stable-alpine}
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: ${NGINX_WEB_SEVICE_NAME:-nginx-proxy-automation-web}
    restart: always
    ports:
      - "${IPv4:-0.0.0.0}:${DOCKER_HTTP_:-80}:80"
      - "${IPv4:-0.0.0.0}:${DOCKER_HTTPS:-443}:443"
      - "${IPv6:-::0}:${DOCKER_HTTP_:-80}:80"
      - "${IPv6:-::0}:${DOCKER_HTTPS:-443}:443"
    environment:
      SSL_POLICY: ${SSL_POLICY:-Mozilla-Intermediate}
      ENABLE_IPV6: "true"
    volumes:
      - ${NGINX_FILES_PATH:-./data}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH:-./data}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH:-./data}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH:-./data}/certs:/etc/nginx/certs:ro
      - ${NGINX_FILES_PATH:-./data}/htpasswd:/etc/nginx/htpasswd:ro
    logging:
      driver: ${NGINX_WEB_LOG_DRIVER:-json-file}
      options:
        max-size: ${NGINX_WEB_LOG_MAX_SIZE:-4m}
        max-file: ${NGINX_WEB_LOG_MAX_FILE:-10}

  nginx-proxy-automation-gen:
    image: jwilder/docker-gen:${DOCKER_GEN_IMAGE_VERSION:-latest}
    command: -notify-sighup ${NGINX_WEB_SEVICE_NAME:-nginx-proxy-automation-web} -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: ${DOCKER_GEN_SEVICE_NAME:-nginx-proxy-automation-gen}
    restart: always
    volumes:
      - ${NGINX_FILES_PATH:-./data}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH:-./data}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH:-./data}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH:-./data}/certs:/etc/nginx/certs:ro
      - ${NGINX_FILES_PATH:-./data}/htpasswd:/etc/nginx/htpasswd:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    logging:
      driver: ${NGINX_GEN_LOG_DRIVER:-json-file}
      options:
        max-size: ${NGINX_GEN_LOG_MAX_SIZE:-2m}
        max-file: ${NGINX_GEN_LOG_MAX_FILE:-10}

  nginx-proxy-automation-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:${NGINX_PROXY_COMPANION_IMAGE_VERSION:-2.0}
    container_name: ${LETS_ENCRYPT_SEVICE_NAME:-nginx-proxy-automation-letsencrypt}
    restart: always
    volumes:
      - ${NGINX_FILES_PATH:-./data}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH:-./data}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH:-./data}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH:-./data}/certs:/etc/nginx/certs:rw
      - ${NGINX_FILES_PATH:-./data}/acme.sh:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: ${DOCKER_GEN_SEVICE_NAME:-nginx-proxy-automation-gen}
      NGINX_PROXY_CONTAINER: ${NGINX_WEB_SEVICE_NAME:-nginx-proxy-automation-web}
      DEFAULT_EMAIL: ${DEFAULT_EMAIL:-mail@yourdomain.tld}
    logging:
      driver: ${NGINX_LETSENCRYPT_LOG_DRIVER:-json-file}
      options:
        max-size: ${NGINX_LETSENCRYPT_LOG_MAX_SIZE:-2m}
        max-file: ${NGINX_LETSENCRYPT_LOG_MAX_FILE:-10}

networks:
  default:
    external:
      name: ${NETWORK:-proxy}
```
