### ISSUE TITLE
Understanding the internal mapping

### ISSUE THREAD

**Issue by Honest-Objections** [evertramos/nginx-proxy-automation#296]
Hello! Thanks for the work on this project as a preface, I must admit, I'm finding a bit of a learning curve trying to glue things together and have hit an impass with my current knowledge. So..

I'm trying to get home assistant setup, to be proxied from the outside world. Here is the `docker-compose` relevant bits:

```yaml
networks:
  proxy:
    external: true

  homeassistant:
    privileged: true
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    devices:
      - ${ZWAVE_USB}:/dev/zwaveusb
    volumes:
      - ./services/home_assistant:/config
    restart: always
    environment:
      - TZ=${TZ}
      - VIRTUAL_HOST=homeassistant.${DOMAIN_NAME}
      - LETSENCRYPT_HOST=homeassistant.${DOMAIN_NAME}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - VIRTUAL_PORT=8123
    depends_on:
      - deconz
    networks:
      - ${PROXY_NETWORK}
    ports:
      - 8123:8123
```

This then generates the following in the nginx `default.conf`:
```
server {
        ...
        location / {
                proxy_pass http://homeassistant.my.domain;
        }
}
```

Obviously this then redirects back to http, so when I try and access it, I get "too many redirects" warning. So, I could manually edit this, but that seems to defeat the point. What am I missing?
