### ISSUE TITLE
Running portainer

### ISSUE THREAD

**Issue by syntaxgirl** [evertramos/nginx-proxy-automation#342]
I tried to setup portainer on my server, but it fails. It does work on port 9000 if I try to map 9000:9000 port. Portainer also have it's own ssl certificate and running both http, and https server, so it's harder to make it work. Any tip?

Here is a portainer docs https://docs.portainer.io/v/ce-2.11/start/upgrade/docker

This is my docker-compose.yml file
```
version: '3'

services:
  portainer:
    image: portainer/portainer-ce:2.11.0
    container_name: portainer
    hostname: example.com
    environment:
      - VIRTUAL_HOST=example.com
      - LETSENCRYPT_HOST=example.com
      - LETSENCRYPT_EMAIL=example@example.com
      - VIRTUAL_PORT=80
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    ports:
      - 9000:9000
      - 8000:8000
    expose:
      - 9000
      - 8000
    networks:
      - proxy

networks:
  proxy:
    external: true
```

**Comment by evertramos** [comment]
Hello @syntaxgirl!

Have you tried:

https://github.com/evertramos/docker-portainer-letsencrypt

**Comment by syntaxgirl** [comment]
> Hello @syntaxgirl!
> 
> Have you tried:
> 
> https://github.com/evertramos/docker-portainer-letsencrypt

Well this is something I didn't know existed. Works like a charm now. Thank you very much!

**Comment by asimzeeshan** [comment]
@syntaxgirl the issue is in your docker-compose.yml file

instead of 
` - VIRTUAL_PORT=80`

you need to use the 9000 port which portainer listens to
` - VIRTUAL_PORT=9000`

You also don't need the ports and the expose section. A simplified portainer behind the proxy would look something like this

```
---

version: '3'

services:
  portainer:
    image: portainer/portainer-ee
    container_name: portainer
    restart: always
    environment:
      - VIRTUAL_HOST=portainer.example.com
      - LETSENCRYPT_HOST=portainer.example.com
      - LETSENCRYPT_EMAIL=docker@example.com
      - VIRTUAL_PORT=9000
    ports:
      - "8000:8000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/:/data

networks:
    default:
        name: proxy
```

Port 8000 is exposed intentionally because that may be needed for a portainer-agent if you choose to monitor your other machine's as well
