### ISSUE TITLE
[BUG] No live upstreams while connecting to upstream

### ISSUE THREAD

**Issue by NgLoader** [evertramos/nginx-proxy-automation#345]
**Describe the bug**
Unable to connect.
Getting a 502 Bad Gateway.

**To Reproduce**
1. Startup proxy
2. Startup seafile
3. Open defined page
4. See 502 Bad Gateway error

**Expected behavior**
Redirected to seafile container

**Screenshots**
If the error is in one of the scripts, an screen show will help a lot to identify which part of the script the error occurred. 

**Server info (please complete the following information):**
 - Linux release: Debian 11 (SMP Debian 4.9.272-2 (2021-07-19) x86_64)
 - Server type: 4.9.0-16-amd64
 - Docker version: 20.10.12, build e91ed57
 - docker-compose version: 1.29.2, build 5becea4c

**Additional context**
```yaml
proxy-web-auto      | 2021/12/26 02:41:43 [error] 90#90: *29 no live upstreams while connecting to upstream, client: 9*.**.98.**, server: seafile.***.eu, request: "GET /favicon.ico HTTP/2.0", upstream: "http://f62d05b96f8cd*******e1c4c45386/favicon.ico", host: "seafile.***.eu", referrer: "https://seafile.***.eu/"
```
**Seafile compose file**
```yaml
version: '2.0'
services:
  db:
    image: mariadb:10.5
    restart: always
    container_name: seafile-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=***
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - ./seafile-mysql/db:/var/lib/mysql
    networks:
      - seafile-net

  memcached:
    image: memcached:1.5.6
    restart: always
    container_name: seafile-memcached
    entrypoint: memcached -m 256
    networks:
      - seafile-net

  elasticsearch:
    image: seafileltd/elasticsearch-with-ik:5.6.16
    restart: always
    container_name: seafile-elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
    volumes:
      - ./seafile-elasticsearch/data:/usr/share/elasticsearch/data
    networks:
      - seafile-net

  seafile:
    image: docker.seadrive.org/seafileltd/seafile-pro-mc:latest
    restart: always
    container_name: seafile
    volumes:
      - ./seafile-data:/shared
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=***
      - TIME_ZONE=Europe/Berlin
      - SEAFILE_ADMIN_EMAIL=mail@***.eu
      - SEAFILE_ADMIN_PASSWORD=***
      - SEAFILE_SERVER_LETSENCRYPT=false
      - SEAFILE_SERVER_HOSTNAME=seafile.***.eu
      - VIRTUAL_NETWORK=proxy
      - VIRTUAL_HOST=seafile.***.eu
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=seafile.***.eu
      - LETSENCRYPT_EMAIL=mail@***.eu
    depends_on:
      - db
      - memcached
      - elasticsearch
    networks:
      - seafile-net

networks:
    seafile-net:
    default:
       external:
         name: proxy
```
