### ISSUE TITLE
504 Gateway timeout

### ISSUE THREAD

**Issue by cod3rshotout** [evertramos/nginx-proxy-automation#348]
Hi,

I'm trying to run a really long script over `nginx-proxy-automation`, after 60s I get from nginx this error:

> 504 Gateway timeout 

I tried to fix this increasing the timeout value in the `proxy-web-auto` container, so I have created a new file within the `conf.d` folder called `timeout.conf` with the following content:

```
[proxy_read_timeout 600s;
fastcgi_read_timeout 600s;
```

In this way the script should run for 10 minutes max.

Then I executed this command: `docker-compose down -v` and `docker-compose up --build` and tested again the script, but again, after a minute the same nginx error.

The app, run over `php-fpm` and `nginx` and I have two container:

```
version: '3.9'

services:

  bcm-fpm:
    container_name: bcm_app
    restart: always
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    volumes:
      - ./src:/var/www/html
      - ./docker/php-fpm/config/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./src/public:/bcm_app/public

  nginx:
    image: nginx:stable-alpine
    container_name: bcm_nginx
    restart: always
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - bcm-fpm
    environment:
      VIRTUAL_HOST: ${HOST}
      LETSENCRYPT_HOST: ${HOST}
      LETSENCRYPT_EMAIL: ${EMAIL}
```

This the nginx configuration:

*docker/nginx/conf.d/default.conf*

```
upstream php-upstream {
    server bcm-fpm:9000;
}
```

*docker/nginx/site/default.conf*

```
server {
    root   /var/www/html;
    index index.php;
    
    add_header Access-Control-Allow-Origin *;

    location / {
        add_header Access-Control-Allow-Origin *;
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ [^/]\.php(/|$) {
        add_header Access-Control-Allow-Origin *;
        fastcgi_split_path_info ^(.+?\.php)(/.*)$;

        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO       $fastcgi_path_info;
        fastcgi_param PATH_TRANSLATED $document_root$fastcgi_path_info;

        fastcgi_pass   php-upstream;
        fastcgi_index  index.php;
    }
}
```

*docker/nginx/nginx.conf*

```
user  nginx;
worker_processes  4;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    client_max_body_size 100M;

    access_log  /var/log/nginx/access.log;
    # Switch logging to console out to view via Docker
    #access_log /dev/stdout;
    #error_log /dev/stderr;

    sendfile        on;
    keepalive_timeout  65;
    
    include /etc/nginx/conf.d/*.conf;
    include /etc/nginx/sites-available/*.conf;
}
```

How can I fix this problem?
