### ISSUE TITLE
[BUG] no live upstreams while connecting to upstream

### ISSUE THREAD

**Issue by fractalf** [evertramos/nginx-proxy-automation#391]
Hi, I'm trying to move my 3 year old setup to a new server and can't the this to work anymore..

```
2024/01/14 20:20:28 [error] 62#62: *138 no live upstreams while connecting to upstream, client: <ip>, server: <host>, request: "GET /favicon.ico HTTP/2.0", upstream: "http://<host>/favicon.ico", host: "<host>", referrer: "https://<host>/"
```

I know there's a couple of other closed issues regarding this, but I think I did everything right, so what could be wrong here?

```sh
version: "3.7"

services:
    matrix:
        container_name: matrix
        image: matrixdotorg/synapse:v1.98.0
        user: 1000:1000
        volumes:
            - matrix:/data
        networks:
            - proxy
        environment:
            # For ngix-proxy:
            VIRTUAL_HOST: <host>
            VIRTUAL_PORT: 5000
            LETSENCRYPT_HOST: <host>
            LETSENCRYPT_EMAIL: <email>
        ports:
            - 5000:80
        restart: always

networks:
  proxy:
    external: true

volumes:
    matrix:
        driver_opts:
            type: none
            o: bind
            device: /<path>/matrix
```

The network seems to be good

```
$ docker network ls
NETWORK ID     NAME      DRIVER    SCOPE
62ef689585e6   bridge    bridge    local
392876e4ba79   host      host      local
bb43682b678b   none      null      local
b7285d5ef29b   proxy     bridge    local
```

**Comment by evertramos** [comment]
Hello @fractalf, have you check the proxy containers? are they all running? what are their logs? did you test the domain with the test script? did it work? your setup seems to be fine, if all services are working, stop your service, wait untill it removes from the nginx defaul.conf file and try again.

**Comment by fractalf** [comment]
Hi @evertramos and thanks a lot for responding :)

In my desperation yesterday I set out to also try out the "default" `nginx-proxy/nginx-proxy`  setup to see if there was something I missed. I got the same problems there, and got some good help pinpointing out what I was doing wrong (ref. https://github.com/nginx-proxy/nginx-proxy/issues/2374)

I tried this here as well, and voila it worked! So my bad odc, my `docker-compose.yml` wasn't right after all

Here's the correct working one for reference, in case others stumble upon this

```yml
version: "3.7"

services:
    matrix:
        container_name: matrix
        image: matrixdotorg/synapse:v1.98.0
        volumes:
            - matrix:/data
        environment:
            VIRTUAL_HOST: <redacted host>
            VIRTUAL_PORT: 8008
            LETSENCRYPT_HOST: <redacted host>
        restart: always

networks:
  default:
    name: proxy
    external: true

volumes:
    matrix:
        driver_opts:
            type: none
            o: bind
            device: /home/alf/docker-data/matrix
```

Cheers, closing this..
